all: seccamp2014.7z

seccamp2014.7z:
	cp ../generate4/seccamp2014.gz,v ./seccamp2014.gz,v
	7z a -phanayamata -mhe=on -mx=9 seccamp2014.7z seccamp2014.gz,v

clean:
	rm -f seccamp2014.gz,v seccamp2014.7z
